[package]
name = "rsink"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.62"
config = "0.13.2"
dirs = "4.0.0"
lazy_static = "1.4.0"
notify = "5.0.0"
rust-s3 = { version = "0.32.3", default-features = false, features = ["sync", "tags", "sync-rustls-tls"] }
spinners = "4.1.0"
